---
apiVersion: v1
kind: Namespace
metadata:
  name: oomie
  labels:
    app: oomie

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: oomie
  namespace: oomie
  labels:
    app: oomie

---
apiVersion: policy/v1beta1
kind: PodSecurityPolicy
metadata:
  name: psp-00-oomie
  labels:
    app: oomie
  annotations:
    seccomp.security.alpha.kubernetes.io/defaultProfileName: runtime/default
    seccomp.security.alpha.kubernetes.io/allowedProfileNames: runtime/default
spec:
  allowedHostPaths:
    - pathPrefix: /dev/kmsg
  fsGroup:
    rule: RunAsAny
  hostNetwork: false
  privileged: true
  runAsUser:
    rule: RunAsAny
  seLinux:
    rule: RunAsAny
  supplementalGroups:
    rule: RunAsAny
  volumes:
    - hostPath
    - secret

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: oomie
  labels:
    app: oomie
rules:
  - apiGroups: [""]
    resources: ["pods"]
    verbs:     ["list","get","watch"]
  - apiGroups: [""]
    resources: ["events"]
    verbs:     ["patch","create"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: oomie
  labels:
    app: oomie
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: oomie
subjects:
  - kind: ServiceAccount
    name: oomie
    namespace: oomie

---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: oomie
  namespace: oomie
  labels:
    app: oomie
rules:
  - apiGroups:
      - policy
    resourceNames:
      - psp-00-oomie
    resources:
      - podsecuritypolicies
    verbs:
      - use

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: oomie
  namespace: oomie
  labels:
    app: oomie
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: oomie
subjects:
  - kind: ServiceAccount
    name: oomie
    namespace: oomie

---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: oomie
  namespace: oomie
  labels:
    app: oomie
spec:
  selector:
    matchLabels:
      app: oomie
  updateStrategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 10%
  template:
    metadata:
      labels:
        app: oomie
    spec:
      tolerations:
        - operator: Exists
      serviceAccountName: oomie
      containers:
        - name: oomie
          securityContext:
            runAsUser: 0
            privileged: true
          env:
            - name: NODENAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
          image: faizank/oomie:2.0
          volumeMounts:
            - name: kernel-logs
              mountPath: "/dev/kmsg"
      volumes:
        - name: kernel-logs
          hostPath:
            path: "/dev/kmsg"
            type: CharDevice

